name: Homebrew Release
on:
  repository_dispatch:
    types:
      - webhook
jobs:
  release-cli:
    name: Release CLI
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - name: openbsd
            architecture: arm64
            version: '7.2'
            host: macos-12

          - name: openbsd
            architecture: x86-64
            version: '7.2'
            host: macos-12

          - name: openbsd
            architecture: x86-64
            version: '7.2'
            host: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.PR_APP_ID }}
          private_key: ${{ secrets.PR_APP_PRIVATE_KEY }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-static-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn
      - name: Update CLI
        run: yarn update-fragment-cli-version --stage ${{ github.event.client_payload.stage }} --cli-version ${{ github.event.client_payload.version }}
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Brew Install Fragment CLI Beta on ${{ matrix.os.host}} ${{ matrix.os.architecture }} ${{ matrix.os.name }}
        if: ${{ github.event.client_payload.stage == 'dev' }}
        uses: cross-platform-actions/action@v0.10.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          run: |
            brew install --build-from-source ./Formula/fragment-cli-beta.rb
            echo "Fragment CLI installed"
            fragment --version
      - name: Brew Install Fragment CLI Prod ${{ matrix.os.host}} ${{ matrix.os.architecture }} ${{ matrix.os.name }}
        if: ${{ github.event.client_payload.stage == 'prod' }}
        uses: cross-platform-actions/action@v0.10.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          run: |
            brew install --build-from-source ./Formula/fragment-cli.rb
            echo "Fragment CLI installed"
            fragment --version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update FRAGMENT CLI in stage ${{ github.event.client_payload.stage }} to version ${{ github.event.client_payload.version }}
          title: Update FRAGMENT CLI ${{ github.event.client_payload.stage }} ${{ github.event.client_payload.version }}
          delete-branch: true
          branch: update-cli/${{ github.event.client_payload.stage }}
          base: 'main'
          body: >
            This PR is auto-generated by a github action.
          labels: automated pr, ${{ github.event.client_payload.stage }}
